Update splash-term to use --auto to be called from udev rule

diff --git a/sbin/splash-term b/sbin/splash-term
--- a/sbin/splash-term
+++ b/sbin/splash-term
@@ -3,31 +3,106 @@
 ME=$(basename $0)
 
 splash_ctl=fbcondecor_ctl.static
+LOG_FILE=/var/log/$ME.log
 
-case $# in
-    1 ) term=$(fgconsole); theme="$1";;
-    2 ) term="$1"; theme="$2";;
+usage() {
+    local ret=${1:0}
+    cat <<Usage
+Usage: $ME [options] [1-6] theme
+Set the background console decoration on one virtual console
 
-    * ) echo "usage: splash_term [1-6] theme"
-        echo "Set the fbsplash theme on specified vconsole or the current one."
-        echo
-        echo "themes:"
-        /bin/ls /etc/splash
-        exit ;;
-esac
+Options:
+    -a --auto     Only run if a splash= boot parameter was given.
+                  Set vt to 1, set theme to default or as defined
+                  in the splash boot parameter
+                  Log messages to $LOG_FILE
+    -h --help     Show this help
+    -q --quiet    Supress messages
 
-which $splash_ctl &>/dev/null || exit
+Themes:
+$(list_themes)
+Usage
+    exit $ret
+}
 
-if [ ! -d /etc/splash/$theme ]; then
-    echo "Theme \"$theme\" not found"
-    echo
-    echo "Valid themes:"
-    /bin/ls /etc/splash
-    exit 1
-fi
+main() {
 
-echo "$ME $term -> $theme"
+    local param
+    while [ $# -gt 0 -a -n "$1" -a -z "${1##-*}" ]; do
+        param=${1#-}
+        shift
+        case $param in
+            -auto|a) do_auto_mode  ; exit 0 ;;
+            -help|h) usage                  ;;
+           -quiet|q) QUIET_MODE=true        ;;
+        esac
+    done
 
-$splash_ctl --tty="${term}" -t "${theme}" -c setcfg 2>/dev/null
-$splash_ctl --tty="${term}" -t "${theme}" -c setpic 2>/dev/null
-$splash_ctl --tty="${term}" -c on
+    case $# in
+        0) usage                           ;;
+        1) term=$(fgconsole); theme=$1     ;;
+        2) term=$1; theme=$2               ;;
+        *)  error "Extra command line parameters" ;;
+    esac
+
+    which $splash_ctl &>/dev/null || error "Could not find program $splash_ctl"
+
+    if [ ! -d /etc/splash/$theme ]; then
+        cat <<Theme_Not_Found >&2
+$ME Error: Theme "$theme" not found.
+Valid themes:
+$(list_themes)
+Theme_Not_Found
+         exit 1
+    fi
+
+    case $term in
+        [1-9]|[1-6][0-9]) ;;
+            *) error "Invalid console number: $term" ;;
+    esac
+
+    set_splash $term "$theme"
+}
+
+set_splash() {
+    local term=$1  theme=$2
+    [ "$QUIET_MODE" ] || echo "$ME $term -> $theme"
+    $splash_ctl --tty=$term -t "$theme" -c setcfg 2>/dev/null
+    $splash_ctl --tty=$term -t "$theme" -c setpic 2>/dev/null
+    $splash_ctl --tty=$term -c on
+}
+
+do_auto_mode() {
+    read_splash_param
+    [ "$SPLASH" ]  || exit 0
+    set_splash 1 ${THEME:-default} >> $LOG_FILE
+}
+
+read_splash_param() {
+    local param sparam
+    for param in ${CMDLINE:-$(cat /proc/cmdline)}; do
+        case $param in
+            splash)  SPLASH=on ;;
+          splash=*)  SPLASH=$SPLASH${SPLASH:+,}${param#*=} ;;
+        esac
+    done
+
+    for sparam in ${SPLASH//,/ }; do
+        case $sparam in
+            theme=*|t=*) THEME=${sparam#*=} ;;
+                    off) SPLASH=            ;;
+        esac
+    done
+}
+
+list_themes() {
+    local width=$(stty size 2>/dev/null | cut -d" " -f2)
+    /bin/ls /etc/splash | column -x -c $((width - 2))
+}
+
+error() {
+    echo "$ME Error: $*" >&2
+    exit 2
+}
+
+main "$@"
