Update perist scripts.  See Persist-scripts log

diff --git a/usr/local/bin/persist-makefs b/usr/local/bin/persist-makefs
--- a/usr/local/bin/persist-makefs
+++ b/usr/local/bin/persist-makefs
@@ -15,7 +15,6 @@ SAFETY_MARGIN=10
     VFAT_MKFS_SIZES="250 375 500 750 1000 1500 2000 2500 3000 4000"
          MKFS_SIZES="250 375 500 750 1000 1500 2000 2500 3000 4000 5000 6000"
    MKFS_FREE_MARGIN=20
-       SCREEN_WIDTH=$(stty size 2>/dev/null | cut -d" " -f2)
 
 # Files listed on the main screen
 ACTIVE_FILES="rootfs rootfs.bak homefs homefs.new homefs.old rootfs.old linuxfs.old"
@@ -151,7 +150,7 @@ main() {
 
         gather_device_info
         vmsg "Make rootfs.new"
-        make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")" ""
+        make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")"
         exit
 
     elif [ "$SET_EXPLORE" ]; then
@@ -220,7 +219,7 @@ main() {
 
             $MAKE_ROOTFS)
                 vmsg "Make rootfs"
-                make_filefs rootfs "$(gt "Create Root")" ""
+                make_filefs rootfs "$(gt "Create Root persistence")"
                 ;;
 
             $RESIZE_ROOTFS)
@@ -232,15 +231,15 @@ main() {
                     continue
                 fi
                 vmsg "Resize rootfs"
-                make_filefs rootfs.tmp "$(gt "Resize Root")" "${USED_SPACE[rootfs]}"  && continue
+                make_filefs rootfs.tmp "$(gt "Resize Root persistence")" || continue
 
-                if ! [ "$MADE_FS" = "rootfs.tmp" ]; then
-                    noisy_yes_no_box "$TITLE" "" \
-                        "$(gt "The resize rootfs has failed.")" \
-                        "$(pfgt "Shall I delete the %s file?" "[f]rootfs.tmp[/]")" \
-                        && rm -f $rootfs.tmp
-                    continue
-                fi
+                # if ! [ "$MADE_FS" = "rootfs.tmp" ]; then
+                #     noisy_yes_no_box "$TITLE" "" \
+                #         "$(gt "The resize rootfs has failed.")" \
+                #         "$(pfgt "Shall I delete the %s file?" "[f]rootfs.tmp[/]")" \
+                #         && rm -f $rootfs.tmp
+                #     continue
+                # fi
                 copy_filefs "$rootfs" "$rootfs.tmp" "${USED_SPACE[rootfs]}" || continue
                 mv -f $rootfs $rootfs.bak
                 mv -f $rootfs.tmp $rootfs
@@ -248,19 +247,18 @@ main() {
 
             $MAKE_ROOTFS_NEW)
                 vmsg "Make rootfs.new"
-                make_filefs rootfs.new "$(gt "Create rootfs.new (for remastering)")" ""
+                make_filefs rootfs.new "$(gt "Create %s (for remastering)" rootfs.new)"
                 ;;
 
             $MAKE_HOMEFS)
                 vmsg "Make homefs"
-                make_filefs "homefs" "$(gt "Create Home")" "" "$SAFE_AVAIL" "$(gt "Create Home")"
+                make_filefs "homefs" "$(gt "Create Home persistence")"
                 ;;
 
             $RESIZE_HOMEFS)
                 vmsg "Resize homefs"
                 homefs="$FULL_PATH/homefs"
-                make_filefs "homefs.new" "$(gt "Resize Home")" "" "$SAFE_AVAIL" "$(gt "Resize Home")" \
-                    && continue
+                make_filefs "homefs.new" "$(gt "Resize Home persistence")" || continue
 
                 copy_filefs "$homefs" "$homefs.new" "${USED_SPACE[homefs]}"
                 ;;
@@ -295,7 +293,6 @@ makefs() {
     local file=$1  type=$2  size=$3
     mkdir -p $(dirname $file)                                                    || return 1
     time_cmd_quiet dd if=/dev/zero of=$file bs=1M count=0 seek=$size             || return 2
-    sync
     time_cmd_quiet mkfs.$type -F $file                                           || return 3
 }
 
@@ -322,58 +319,59 @@ select_ftype() {
 }
 
 make_filefs() {
-    local file=$1  ptype=$2  min_size=$3  max_size=${4:-$MAX_SIZE}
-
+    local file=$1  ptype=$2
+    local min_size=250 max_size=$MAX_SIZE
     local full="$FULL_PATH/$file"
-    #vmsg "make_filefs(\"$1\", \"$2\", \"$3\", \"$4\")"
     if [ -f "$full" ]; then
         yes_no_box "$TITLE" ""                                       \
             "$(pfgt "The file %s already exists" "[f]$file[/]")" ""  \
-            "${INFO_HASH[$file]}" ""                                 \
             "$(gt "Do you want to over-write it?")" ""               \
             || return 0
     fi
 
-    local text="$(gt "Please select size of the new file system")\n\n$(pfgt "For %s persistence" "[b]$file[/]")"
+    local text="$ptype\n\n$(gt "Please select size of the new file system")"
     if ! select_size -min "$min_size" -Max "$max_size" "" "$text"; then
-        warn_box "$TITLE" "" \
-            "$(pfgt "Not enough space on device to %s" "$ptype")" ""
-
+        warn_box "$TITLE" "" "$(pfgt "Not enough space on device")" ""
         return
     fi
     local size=$UI_RESULT
 
     #select_ftype
     FTYPE=ext4
-    vmsg "FTYPE=$FTYPE"
-    local last_line=$(gt "Please wait")
-    [ "$DEV_FS" = vfat ] && \
-        last_line=$(pfgt "Warning: this can take several minutes per Gig on a %s file system" "[b]$DEV_FS[/b]")
+    vmsg "filesystem type: $FTYPE"
+    local last_line
+
+    case $DEV_FS in
+        vfat) last_line=$(pfgt "Warning: this can take several minutes per Gig on a %s file system" "[b]$DEV_FS[/b]") ;;
+           *) last_line=$(gt "Please wait") ;;
+    esac
 
     make_path_if_needed "$DEV_MP" "$P_PATH"
 
-    bg_info_box -o "$PULSATE"                             \
-        ""                                                \
-        "$(pfgt "Creating file %s" [f]$file[/])"          \
-        "$(pfgt "Size: %s  filesystem: %s" $size $FTYPE)" \
-        ""                                                \
-        "$last_line"                                      \
+    bg_info_box -o "$PULSATE"                                 \
+        ""                                                    \
+        "$(pfgt "Creating file %s" [f]$file[/])"              \
+        "$(pfgt "Size: %s Meg. Filesystem: %s" $size $FTYPE)" \
+        ""                                                    \
+        "$last_line"                                          \
         ""
-
-    kill_bg_info_box
 
     makefs "$full" $FTYPE $size;
     local ret=$?
 
+    kill_bg_info_box
     case $ret in
+        0) ;;
         1) warn_box "" "$(pfgt "Was unable to create directory for file %s"         "[f]$file[/]")"  ;;
         2) warn_box "" "$(pfgt "Was unable to create file %s"                       "[f]$file[/]")"  ;;
         3) warn_box "" "$(pfgt "Was unable to make %s filesystem on file %s" $FTYPE "[f]$file[/]")"  ;;
+        *) warn_box "" "$(pfgt "Unknown error creating file %s"                     "[f]$file[/]")"  ;;
     esac
 
-    [ $ret -eq 0 ] && return $ret
-    rm -f $full
-    return 2
+    if [ $ret -ne 0 ]; then
+        rm -f $full
+        return 2
+    fi
 
     if [ ! -f $full ]; then
         warn_box "" "$(pfgt "The file %s is missing" "[f]$file[/]")"
@@ -766,9 +764,6 @@ gather_device_info() {
     MAX_SIZE=$(min_of $SAFE_RAM $SAFE_AVAIL)
 
     [ "$DEV_FS" = vfat -a $MAX_SIZE -gt 4095 ] && MAX_SIZE=4095
-
-    echo "dev_fs: $DEV_FS"
-    echo "max_size: $MAX_SIZE"
 
     DEVICE_TEXT=(                                                    \
         "[fixed]"                                                    \
